# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"
sudo: false
before_install:
  - gem install bundler
script: "bundle exec rake --trace"
rvm:
  - 2.2.4
  - 2.3.0
  - 2.4.1
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
notifications:
  irc: "irc.freenode.org#savon"
