# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"
script: "bundle exec rake --trace"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
notifications:
  irc: "irc.freenode.org#savon"
