# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"
script: "bundle exec rake --trace"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
notifications:
  irc: "irc.freenode.org#savon"
