# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
bundler_args: --without developer_happiness
script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx
  - rbx-2.0
  - jruby
notifications:
  irc: "irc.freenode.org#savon"
